language: python
python:
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - cd ..
  - coverage run --source=matador setup.py test
  - coverage report -m
after_success:
  - coveralls
